name: flutter_e_commerce
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  #? Utility Package
  http: ^1.3.0
  intl: ^0.19.0
  logger: ^2.5.0
  url_launcher: ^6.3.1
  carousel_slider: ^5.0.0
  flutter_native_splash: ^2.4.4
  lottie: ^3.3.1
  smooth_page_indicator: ^1.2.1
  device_preview: ^1.2.0

  #? Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  #? State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  #? Products specific features
  readmore: ^3.0.0
  carousel_slider_plus: ^7.1.0
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/user/
    - assets/images/reviews/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
